#!/bin/bash

# HBLINK3 DOCKER CONTROL SCRIPTS V2.0
# Version 13122025
# This script written by Shane Daley M0VUB. The script gracefully shuts down services while services are cleaned and logs are truncated.
# We can also add items in this script for future use like updates or further log trims.
# Add to the cron tab for auto execution

#   Copyright (C) 2020-2025 Shane P. Daley  M0VUB <shane@freestar.network>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# Flush routine for HBlink3 (ShaYmez docker only)

# Start service clean/truncate/ and restart of services.

echo "Stopping services....."
sleep 1

echo "Stopping HBlink3 (If not already stopped)...."
cd /etc/hblink3
docker-compose down
echo "Done."
sleep 1

echo "Stopping Dashboard....."
systemctl stop hbmon 
echo "Done."
sleep 1

echo "HBlink3 Flush and maintenance loop starting....."
sleep 1

echo "Starting truncate main log folder /var/log....."
truncate -s 0 /var/log/*log

echo "Starting truncate HBlink3 entire log /var/log/hblink....."
truncate -s 0 /var/log/hblink/*log

echo "Starting truncate Lastheard....."
truncate -s 0 /opt/HBMonv2/log/*log

#Restart all services gracefully
echo "Restart all services....."
sleep 1

echo "Restarting docker app....."
systemctl restart docker
echo "Done."
sleep 1

echo "Restart apache2....."
systemctl restart apache2
echo "Done."
sleep 1

echo "Starting HBlink3....."
sleep 1
echo .
sleep 1
echo ..
sleep 1
echo ...
docker-compose up -d

sleep 1
figlet "HBlink 3" 
sleep 1

echo "Checking HBlink is composed....."
sleep 1
docker ps

sleep 3
echo "Checking startup error logs....."
docker container logs hblink 
echo "Done."

echo "Flushing network tracking table....."
conntrack -F
sleep 1

echo "Starting Dashboard....."
systemctl restart hbmon
figlet "HBMonv2"
echo "Done."
sleep 1

echo "Done. Now Exiting....."
sleep 1
echo .
sleep 1
echo ..
sleep 1
echo ...
echo "HBlink 3 is now online. Flush is complete and you may now exit. AKA ShaYmez."
#
# This script has been developed by the one and only ShaYmez. Visit https://repo.radio/ShaYmez for more super scripts!
echo "All systems have been flushed/cleaned and ready to go. Aka Dr. Node. ShaYmez, HBlink3"
